/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ETXUGRtTNBT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "~/components/ui/card"
import { Avatar } from "~/components/ui/avatar"
import { RadioGroupItem, RadioGroup } from "~/components/ui/radio-group"
import { Label } from "~/components/ui/label"
import { Button } from "~/components/ui/button"
import { Separator } from "~/components/ui/separator"
import { Textarea } from "~/components/ui/textarea"

export function AIChat() {  
  return (
    <div className="flex flex-col min-h-screen">
      <div className="flex-1 flex flex-col items-center justify-center p-4 sm:p-8">
        <Card className="max-w-3xl w-full">
          <CardHeader>
            <CardTitle>AI Career Coach</CardTitle>
            <CardDescription>Let's find your dream job together!</CardDescription>
          </CardHeader>
          <CardContent className="grid gap-4 w-full">
            <div className="flex items-start gap-4">
              <Avatar className="rounded-full w-12 h-12 bg-green-500 text-white"><span className="p-3">🤖</span></Avatar>
              <div className="grid gap-1">
                <div className="font-bold">Welcome!</div>
                <div>I'm an AI-powered career coach. Let's start by understanding your goals and preferences.</div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <Avatar className="rounded-full w-12 h-12 bg-blue-500 text-white"><span className="p-3 pl-3.5">👤</span></Avatar>
              <div className="grid gap-1">
                <div className="font-bold">You</div>
                <div>
                  I'm looking for a challenging role in software engineering, preferably at a tech company where I can
                  work on cutting-edge technologies.
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <Avatar className="rounded-full w-12 h-12 bg-green-500 text-white"><span className="p-3">🤖</span></Avatar>
              <div className="grid gap-1">
                <div className="font-bold">AI Career Coach</div>
                <div>Great! To better understand your preferences, please select one of the following options:</div>
              </div>
            </div>
            <Card>
              <CardContent className="grid gap-2 mt-5">
                <RadioGroup defaultValue="frontend" className="gap-y-4">
                  <Label htmlFor="frontend">
                    <RadioGroupItem id="frontend" value="frontend" />
                    <span className="ml-2">
                      I prefer frontend development (building user interfaces and web applications).
                    </span>
                  </Label>
                  <Label htmlFor="backend">
                    <RadioGroupItem id="backend" value="backend" />
                    <span className="ml-2">
                      I prefer backend development (building server-side applications and APIs).
                    </span>
                  </Label>
                  <Label htmlFor="fullstack">
                    <RadioGroupItem id="fullstack" value="fullstack" />
                    <span className="ml-2">
                      I'm interested in full-stack development (working on both frontend and backend).
                    </span>
                  </Label>
                  <Label htmlFor="other">
                    <RadioGroupItem id="other" value="other" />
                    <span className="ml-2">None of the above (please specify your preferences).</span>
                  </Label>
                </RadioGroup>
              </CardContent>
            </Card>
            <div className="flex items-start gap-4">
              <Avatar className="rounded-full w-12 h-12 bg-green-500 text-white"><span className="p-3">🤖</span></Avatar>
              <div className="grid gap-1">
                <div className="font-bold">AI Career Coach</div>
                <div>
                  Great! Can you tell me more about your skills and experience? It would also be helpful if you could
                  upload your CV or resume.
                </div>
              </div>
            </div>
            <div className="flex items-center justify-center w-full">
              <label
                htmlFor="cv-upload"
                className="flex flex-col items-center justify-center w-full h-64 border-2 border-dashed rounded-lg cursor-pointer bg-gray-800 hover:bg-gray-700 dark:bg-gray-900 dark:hover:bg-gray-800"
              >
                <div className="flex flex-col items-center justify-center pt-5 pb-6">
                  <UploadIcon className="w-10 h-10 mb-3 text-gray-400" />
                  <p className="mb-2 text-sm text-gray-400 dark:text-gray-500">
                    <span className="font-semibold">Click to upload</span> or drag and drop
                  </p>
                  <p className="text-xs text-gray-400 dark:text-gray-500">PDF or Word document</p>
                </div>
                <input id="cv-upload" type="file" className="hidden" accept=".pdf,.doc,.docx" />
              </label>
            </div>
            <div className="flex items-start gap-4">
              <Avatar className="rounded-full w-12 h-12 bg-green-500 text-white"><span className="p-3">🤖</span></Avatar>
              <div className="grid gap-1">
                <div className="font-bold">AI Career Coach</div>
                <div>
                  Based on your preferences and experience, here are some relevant job opportunities that might interest
                  you:
                </div>
              </div>
            </div>
            <div className="grid gap-4">
              <Card>
                <CardHeader>
                  <CardTitle>Senior Software Engineer</CardTitle>
                  <CardDescription>Acme Inc.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">San Francisco, CA</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">Full-time</div>
                    </div>
                    <Button size="sm" variant="outline">
                      Apply Now
                    </Button>
                  </div>
                  <Separator className="my-4" />
                  <div className="text-sm text-gray-500 dark:text-gray-400">
                    We are seeking a talented Senior Software Engineer to join our team and work on cutting-edge AI and
                    machine learning projects. You will be responsible for designing, implementing, and maintaining
                    complex software systems.
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Lead Software Architect</CardTitle>
                  <CardDescription>TechCorp</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">Seattle, WA</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">Full-time</div>
                    </div>
                    <Button size="sm" variant="outline">
                      Apply Now
                    </Button>
                  </div>
                  <Separator className="my-4" />
                  <div className="text-sm text-gray-500 dark:text-gray-400">
                    We are seeking a highly experienced Lead Software Architect to drive the technical vision and
                    strategy for our cutting-edge cloud computing platform. You will work closely with cross-functional
                    teams to design and implement scalable, high-performance systems.
                  </div>
                </CardContent>
              </Card>
            </div>
          </CardContent>
        </Card>
      </div>
      <div className="sticky bottom-0 w-full p-4 bg-white dark:bg-gray-800">
        <div className="relative">
          <Textarea
            className="min-h-[48px] rounded-2xl resize-none p-4 border border-gray-200 border-neutral-400 shadow-sm pr-16 dark:border-gray-800"
            id="message"
            name="message"
            placeholder="Type your message..."
            rows={1}
          />
          <Button className="absolute top-3 right-3 w-8 h-8" disabled size="icon" type="submit">
            <ArrowUpIcon className="w-4 h-4" />
            <span className="sr-only">Send</span>
          </Button>
        </div>
      </div>
    </div>
  )
}

function ArrowUpIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </svg>
  )
}


function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}
