/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wJtd58pAw3q
 */
import Link from "next/link"
import { Input } from "~/components/ui/input"
import { Button } from "~/components/ui/button"
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "~/components/ui/card"
import { Label } from "~/components/ui/label"
import { api } from "~/utils/api"

export function ApplicantDetails({
  id
}: {
  id: number | null
}) {
  if(id === null) {
    return <div>Application not found</div>
  }

  const {data: application} = api.application.getApplication.useQuery({id})



  return (
    <div className="flex flex-col w-full min-h-screen container">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <nav className="flex-col hidden gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 lg:gap-6">
          <Link className="flex items-center gap-2 text-lg font-semibold md:text-base" href="#">
            <BriefcaseIcon className="h-6 w-6" />
            <span className="sr-only">Employer Dashboard</span>
          </Link>
          <Link className="font-bold" href="#">
            Applications
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Positions
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Candidates
          </Link>
        </nav>
        <div className="flex items-center w-full gap-4 md:ml-auto md:gap-2 lg:gap-4">
          <form className="flex-1 ml-auto sm:flex-initial">
            <div className="relative">
              <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
              <Input
                className="pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px]"
                placeholder="Search applications..."
                type="search"
              />
            </div>
          </form>
          <Button className="rounded-full" size="icon" variant="ghost">
            <img
              alt="Avatar"
              className="rounded-full"
              height="32"
              src="/placeholder.svg"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width="32"
            />
            <span className="sr-only">Toggle user menu</span>
          </Button>
        </div>
      </header>
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 py-4 md:gap-8 md:p-10">
        <div className="flex items-center">
          <h1 className="font-semibold text-lg md:text-2xl">Application Details</h1>
        </div>
        <div>
          <Card>
            <CardHeader>
              <CardTitle>Applicant Information</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <div className="space-y-1">
                <Label htmlFor="name">Name</Label>
                <Input defaultValue={application?.user.name} disabled id="name" />
              </div>
              <div className="space-y-1">
                <Label htmlFor="position">Position</Label>
                <Input defaultValue={application?.jobListing.title} disabled id="position" />
              </div>
              <div className="space-y-1">
                <Label htmlFor="date">Date</Label>
                <Input defaultValue={application?.createdAt.toLocaleDateString()} disabled id="date" />
              </div>
            </CardContent>
            <CardFooter>
              <Button size="sm" variant="outline">
                View Resume
              </Button>
            </CardFooter>
          </Card>
        </div>
      </main>
    </div>
  )
}


function BriefcaseIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>
  )
}


function SearchIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
