/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cK3zJI1vxsu
 */
import { Button } from "~/components/ui/button"

export function ProfileSettingsButtons() {
  return (
    <div className="w-full max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
      <div className="lg:grid lg:grid-cols-3 lg:gap-8">
        <div>
          <h2 className="text-3xl font-extrabold tracking-tight text-gray-100 sm:text-4xl">Manage Your Profile</h2>
          <p className="mt-4 max-w-2xl text-xl text-gray-400 lg:mt-2">
            Easily update your personal information, contact details, work experience, education, skills, and CV.
          </p>
        </div>
        <div className="mt-5 lg:mt-0 lg:col-span-2">
          <dl className="space-y-10 sm:space-y-0 sm:grid sm:grid-cols-2 sm:grid-rows-5 sm:gap-x-6 sm:gap-y-10 lg:gap-x-8">
            <div>
              <dt className="text-lg leading-6 font-medium text-gray-100">Personal Information</dt>
              <dd className="mt-2 text-base text-gray-400">
                Update your name, date of birth, and other personal details.
              </dd>
              <Button className="mt-2">Update Personal Information</Button>
            </div>
            <div>
              <dt className="text-lg leading-6 font-medium text-gray-100">Contact Details</dt>
              <dd className="mt-2 text-base text-gray-400">Keep your email, phone number, and address up to date.</dd>
              <Button className="mt-2">Update Contact Details</Button>
            </div>
            <div>
              <dt className="text-lg leading-6 font-medium text-gray-100">Work Experience</dt>
              <dd className="mt-2 text-base text-gray-400">Add your past work experiences and achievements.</dd>
              <Button className="mt-2">Update Work Experience</Button>
            </div>
            <div>
              <dt className="text-lg leading-6 font-medium text-gray-100">Education</dt>
              <dd className="mt-2 text-base text-gray-400">List your educational background and qualifications.</dd>
              <Button className="mt-2">Update Education</Button>
            </div>
            <div>
              <dt className="text-lg leading-6 font-medium text-gray-100">Skills</dt>
              <dd className="mt-2 text-base text-gray-400">Showcase your professional skills and expertise.</dd>
              <Button className="mt-2">Update Skills</Button>
            </div>
            <div>
              <dt className="text-lg leading-6 font-medium text-gray-100">Upload CV</dt>
              <dd className="mt-2 text-base text-gray-400">
                Upload and update your CV for potential employers to view.
              </dd>
              <Button className="mt-2">Upload CV</Button>
            </div>
            <div>
              <dt className="text-lg leading-6 font-medium text-gray-100">Application Status</dt>
              <dd className="mt-2 text-base text-gray-400">
                Track the status of your job applications and receive updates.
              </dd>
              <Button className="mt-2">Check Application Status</Button>
            </div>
          </dl>
        </div>
      </div>
    </div>
  )
}
